spring:
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://database:5432/category
    username: postgres
    password: 123456
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: create-drop
    properties.hibernate.jdbc.lob.non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    mapping-resources:
    - orm-mapping-resources/top-category.xml
  redis:
    host: redis
    post: 6379
